name: Metrics2
on:
  # Schedule daily updates
  schedule: [{cron: "0 6,9,12,15,18,21 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics2.svg
          user: jsmnhou
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 3
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
